;;; .user-lisp-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:



;;; Generated autoloads from argos-translate.el

(autoload 'argos-translate-region "argos-translate"
"Translate selected region or sentence at point." t)
(register-definition-prefixes "argos-translate" '("argos-translate-"))


;;; Generated autoloads from aws-polly.el

(autoload 'aws-polly-region "aws-polly"
"Speak text with AWS polly.

When no region is active the current paragraph is used. When
prefix argument is given ask for voice first.

When ARG is given, allow to select the voice first.

(fn ARG)" t)
(register-definition-prefixes "aws-polly" '("aws-polly-"))


;;; Generated autoloads from bibtex-completion-overrides.el

(register-definition-prefixes "bibtex-completion-overrides" '("malb/bibtex-completion-"))


;;; Generated autoloads from cryptoverif.el

(register-definition-prefixes "cryptoverif" '("cryptoverif" "pcv-"))


;;; Generated autoloads from empx.el

(defvar empx-mode nil
"Non-nil if Empx mode is enabled.
See the `empx-mode' command
for a description of this minor mode.
Setting this variable directly does not take effect;
either customize it (see the info node `Easy Customization')
or call the function `empx-mode'.")
(custom-autoload 'empx-mode "empx" nil)
(autoload 'empx-mode "empx"
"Empx records the cursor position for forward/backward navigation.

This is a global minor mode.  If called interactively, toggle the `Empx
mode' mode.  If the prefix argument is positive, enable the mode, and if
it is zero or negative, disable the mode.

If called from Lisp, toggle the mode if ARG is `toggle'.  Enable the
mode if ARG is nil, omitted, or is a positive number.  Disable the mode
if ARG is a negative number.

To check whether the minor mode is enabled in the current buffer,
evaluate `(default-value \\='empx-mode)'.

The mode's hook is called both when the mode is enabled and when it is
disabled.

(fn &optional ARG)" t)
(register-definition-prefixes "empx" '("empx-"))


;;; Generated autoloads from gc-maybe.el

(autoload 'gc-maybe-log-current "gc-maybe"
"Print current GC statistics." t)
(autoload 'gc-maybe-log-usage "gc-maybe"
"Run `garbage-collect' and print stats about memory usage." t)
(autoload 'gc-maybe "gc-maybe"
"Maybe GC with `garbage-collect-maybe' and 1/`gc-cons-percentage' factor.")
(defvar gc-maybe-mode nil
"Non-nil if Gc-Maybe mode is enabled.
See the `gc-maybe-mode' command
for a description of this minor mode.
Setting this variable directly does not take effect;
either customize it (see the info node `Easy Customization')
or call the function `gc-maybe-mode'.")
(custom-autoload 'gc-maybe-mode "gc-maybe" nil)
(autoload 'gc-maybe-mode "gc-maybe"
"Minor mode for GC strategy.

This is a global minor mode.  If called interactively, toggle the
`Gc-Maybe mode' mode.  If the prefix argument is positive, enable the
mode, and if it is zero or negative, disable the mode.

If called from Lisp, toggle the mode if ARG is `toggle'.  Enable the
mode if ARG is nil, omitted, or is a positive number.  Disable the mode
if ARG is a negative number.

To check whether the minor mode is enabled in the current buffer,
evaluate `(default-value \\='gc-maybe-mode)'.

The mode's hook is called both when the mode is enabled and when it is
disabled.

(fn &optional ARG)" t)
(register-definition-prefixes "gc-maybe" '("gc-maybe-"))


;;; Generated autoloads from helm-ag.el

(autoload 'helm-ag-pop-stack "helm-ag"
"Restore the previous search context from the `helm-ag--context-stack'." t)
(autoload 'helm-ag-clear-stack "helm-ag"
"Clear all entries in the `helm-ag--context-stack'." t)
(autoload 'helm-ag-this-file "helm-ag"
"Do ag with in this file with QUERY.

(fn &optional QUERY)" t)
(autoload 'helm-ag "helm-ag"
"Do ag with in BASEDIR and with QUERY.

(fn &optional BASEDIR QUERY)" t)
(autoload 'helm-do-ag-this-file "helm-ag"
"Execute `helm-do-ag' Search in the current file.

(fn &optional QUERY)" t)
(autoload 'helm-do-ag "helm-ag"
"Execute a `helm-do-ag' search in the specified directory or files.

BASEDIR: An optional directory in which to perform the search. If not
specified, the current directory is used.
TARGETS: A list of files or directories to search. If not provided,
  the user will be prompted to select files.
DEFAULT-INPUT: An optional string that serves as the initial input for
  the search.

The function initializes the helm state, determines the default directory
and target, and sets up the helm source for searching. It handles Windows
specific behavior for path arguments and saves the current context for
subsequent searches.

(fn &optional BASEDIR TARGETS DEFAULT-INPUT)" t)
(autoload 'helm-ag-project-root "helm-ag"
"Execute `helm-ag' in the project directory with optional default input QUERY.

(fn &optional QUERY)" t)
(autoload 'helm-do-ag-project-root "helm-ag"
"Execute `helm-do-ag' in the project directory with optional default input QUERY..

(fn &optional QUERY)" t)
(autoload 'helm-ag-buffers "helm-ag"
"Execute `helm-ag' in all buffers with optional default input QUERY.

(fn &optional QUERY)" t)
(autoload 'helm-do-ag-buffers "helm-ag"
"Execute `helm-do-ag' in all buffers with optional default input QUERY.

(fn &optional QUERY)" t)
(register-definition-prefixes "helm-ag" '("helm-"))


;;; Generated autoloads from helm-baloo.el

(autoload 'helm-baloo "helm-baloo"
"Run `baloosearch'. If ARG is given, set a directory first

(fn &optional ARG)" t)
(register-definition-prefixes "helm-baloo" '("baloo-search" "helm-baloo-"))


;;; Generated autoloads from helm-ddgr.el

(autoload 'helm-ddgr "helm-ddgr"
"Web search interface for Emacs.

(fn &optional SEARCH-TERM)" t)
(autoload 'helm-ddgr-return "helm-ddgr"
"Web search interface for Emacs.

(fn &optional SEARCH-TERM)")
(register-definition-prefixes "helm-ddgr" '("helm-ddgr-"))


;;; Generated autoloads from hotcrp-mode.el

(autoload 'hotcrp-fetch "hotcrp-mode"
"Fetcn an offline review form from a HotCRP web server.

This function should usually be called in an empty buffer, as it
fills the buffer with the review form and switches the buffer's
major mode to hotcrp-mode (which works best when the review form
is the first thing in the buffer).

PAPER specifies the number of the paper to fetch.  It can also be
\"all\" to fetch all papers you are assigned to review, or
\"incomplete\" to fetch all papers you have been assigned to
review and for which you have not yet submitted reviews.

On the first invocation, if hotcrp-default-url is set,
hotcrp-fetch uses that as the URL of the server.  Otherwise,
hotcrp-fetch prompts for a URL.  On subsequent invocations,
hotcrp-fetch uses whatever value of URL was used in the previous
invocation.  When invoked with a prefix argument, however,
hotcrp-fetch always prompts for the URL.

(fn &optional PAPER URL)" t)
(autoload 'hotcrp-mode "hotcrp-mode"
"Major mode for editing HotCRP offline review forms.
\\<global-map>
To enter hotcrp-mode, either visit a file containing a review
form, or fetch one directly from the server by typing
\\[hotcrp-fetch] in an empty buffer.
\\<hotcrp-paper-map>
Once in hotcrp-mode, you can type \\[hotcrp-upload] to upload
your completed reviews to the server.

In a buffer with review forms for multiple papers, you can move
the point to the review for a particular paper with
\\[hotcrp-goto] or \\[imenu].

To view the PDF of a paper, type \\[hotcrp-fetch-pdf].  You can
also load the HotCRP review page for a particular paper in your
browser with \\[hotcrp-browse-paper-url].

When the mouse is hovering over the paper number at the start of
each review, you can additionally use \\[hotcrp-paper-click-reviews] to
navigate the the web page containing everybody else's reviews, or
\\[hotcrp-paper-click-paper] to download and view the PDF of the paper.

\\{hotcrp-mode-map}

In addition to any hooks its parent mode `text-mode' might have run,
this mode runs the hook `hotcrp-mode-hook', as the final or
penultimate step during initialization." t)
(register-definition-prefixes "hotcrp-mode" '("hotcrp-"))


;;; Generated autoloads from kodi.el

(register-definition-prefixes "kodi" '("kodi"))


;;; Generated autoloads from latex-math-yank.el

(register-definition-prefixes "latex-math-yank" '("malb/"))


;;; Generated autoloads from latex-ocr.el

(autoload 'latex-ocr-screenshot "latex-ocr"
"Capture screenshot and send result to Latex-Ocr.

(fn &optional ARG)" t)
(register-definition-prefixes "latex-ocr" '("latex-ocr-"))


;;; Generated autoloads from llama-swap-shell.el

(autoload 'llama-swap-shell-models-from-config "llama-swap-shell"
"Read list models from config file in PATH.

(fn PATH)")
(autoload 'llama-swap-shell-models-from-server "llama-swap-shell"
"Get list of models from the server.")
(autoload 'llama-swap-shell "llama-swap-shell"
"Start an llama-swap shell.

When ARG is given, prompt the user for a model.

(fn &optional ARG)" t)
(register-definition-prefixes "llama-swap-shell" '("llama-swap-shell-"))


;;; Generated autoloads from llm-prompts.el

(register-definition-prefixes "llm-prompts" '("malb/reply-to-email-llm"))


;;; Generated autoloads from math-delimiters.el

(autoload 'math-delimiters-no-dollars "math-delimiters"
"Convert math formulas in buffer from dollars to \\(\\) and
\\=\\[\\]." t)
(autoload 'math-delimiters-toggle "math-delimiters"
"Toggle between $...$ and \\(...\\) for inline math.
When ARG is non-nil (interactively, if called with universal
prefix argument), also toggle the display math delimiters between
$$...$$ and \\=\\[...\\].

(fn ARG)" t)
(autoload 'math-delimiters-insert "math-delimiters"
"Insert math delimiters.
If region is active surround it.  When repeated, toggle between
display and inline math.  Also toggle between display and inline
if called from inside empty math delimiters, or just after math
delimiters." t)
(register-definition-prefixes "math-delimiters" '("math-delimiters-"))


;;; Generated autoloads from mathpix.el

(register-definition-prefixes "mathpix" '("mathpix-"))


;;; Generated autoloads from ox-inline-comments.el

(register-definition-prefixes "ox-inline-comments" '("malb/o"))


;;; Generated autoloads from pari/pari.el

(autoload 'gp-script-mode "pari/pari"
"Major mode for editing GP input files.

The following bindings are available:
\\{gp-script-map}" t)
(autoload 'gp-mode "pari/pari"
"Major mode for running a gp-process.

The following bindings are available:
\\{gp-map}

(fn &optional NO-FONTIFICATIONP)" t)
(register-definition-prefixes "pari/pari" '("GP-" "buffer-visiblep" "file-really-exists-p" "pari-m"))


;;; Generated autoloads from pari/pari-completion.el

(register-definition-prefixes "pari/pari-completion" '("gp-" "name-extension" "standard-string="))


;;; Generated autoloads from pari/pari-conf.el

(register-definition-prefixes "pari/pari-conf" '("gp-"))


;;; Generated autoloads from pari/pari-fontification.el

(register-definition-prefixes "pari/pari-fontification" '("gp-" "pari-fontification-keywords"))


;;; Generated autoloads from pari/pari-help.el

(autoload 'gpman "pari/pari-help"
"Start up xdvi with the gp manual." t)
(register-definition-prefixes "pari/pari-help" '("gp-"))


;;; Generated autoloads from pari/pari-history.el

(register-definition-prefixes "pari/pari-history" '("add-" "gp-" "head-tail-void" "list-" "ptr-to-" "remove-" "set-ptr-"))


;;; Generated autoloads from pari/pari-messages.el

(register-definition-prefixes "pari/pari-messages" '("gp-"))


;;; Generated autoloads from piper.el

(autoload 'piper-region "piper"
"Speak text with Piper.

When no region is active the current paragraph is used. When
prefix argument is given ask for voice first.

When ARG is given, allow to select the voice first.

(fn ARG)" t)
(register-definition-prefixes "piper" '("piper-"))


;;; Generated autoloads from skip-buffers-mode.el

(defvar skip-buffers-mode nil
"Non-nil if Skip-Buffers mode is enabled.
See the `skip-buffers-mode' command
for a description of this minor mode.")
(custom-autoload 'skip-buffers-mode "skip-buffers-mode" nil)
(autoload 'skip-buffers-mode "skip-buffers-mode"
"Skip buffers you don't want to see.

This is a global minor mode.  If called interactively, toggle the
`Skip-Buffers mode' mode.  If the prefix argument is positive, enable
the mode, and if it is zero or negative, disable the mode.

If called from Lisp, toggle the mode if ARG is `toggle'.  Enable the
mode if ARG is nil, omitted, or is a positive number.  Disable the mode
if ARG is a negative number.

To check whether the minor mode is enabled in the current buffer,
evaluate `(default-value \\='skip-buffers-mode)'.

The mode's hook is called both when the mode is enabled and when it is
disabled.

(fn &optional ARG)" t)
(register-definition-prefixes "skip-buffers-mode" '("skip-buffers-"))


;;; Generated autoloads from pari/sli-tools.el

(register-definition-prefixes "pari/sli-tools" '("sli-"))


;;; Generated autoloads from snapshot-timemachine.el

(autoload 'snapshot-timemachine "snapshot-timemachine"
"Start the snapshot timemachine for FILE.
FILE defaults to the file the current buffer is visiting.

(fn &optional FILE)" t)
(autoload 'snapshot-timeline "snapshot-timemachine"
"Display a timeline of snapshots of FILE.
FILE defaults to the file the current buffer is visiting.

(fn &optional FILE)" t)
(register-definition-prefixes "snapshot-timemachine" '("snapshot-" "with-A-B"))


;;; Generated autoloads from tesseract.el

(autoload 'tesseract-screenshot "tesseract"
"Capture screenshot and send result to Tesseract." t)
(register-definition-prefixes "tesseract" '("tesseract-"))


;;; Generated autoloads from typo.el

(autoload 'typo-mode "typo"
"Minor mode for typographic editing.

This mode changes some default keybindings to enter typographic
glyphs. In particular, this changes how quotation marks, the
dash, the dot, and the angle brackets work.

Most keys will cycle through various options when used
repeatedly.

\\{typo-mode-map}

This is a minor mode.  If called interactively, toggle the `Typo mode'
mode.  If the prefix argument is positive, enable the mode, and if it is
zero or negative, disable the mode.

If called from Lisp, toggle the mode if ARG is `toggle'.  Enable the
mode if ARG is nil, omitted, or is a positive number.  Disable the mode
if ARG is a negative number.

To check whether the minor mode is enabled in the current buffer,
evaluate the variable `typo-mode'.

The mode's hook is called both when the mode is enabled and when it is
disabled.

(fn &optional ARG)" t)
(defvar typo-global-mode nil
"Non-nil if Typo-Global mode is enabled.
See the `typo-global-mode' command
for a description of this minor mode.")
(custom-autoload 'typo-global-mode "typo" nil)
(autoload 'typo-global-mode "typo"
"Minor mode for typographic editing.

This mode provides a prefix map under C-c 8 which complements the
default C-x 8 prefix map.

\\{typo-global-mode-map}

This is a global minor mode.  If called interactively, toggle the
`Typo-Global mode' mode.  If the prefix argument is positive, enable the
mode, and if it is zero or negative, disable the mode.

If called from Lisp, toggle the mode if ARG is `toggle'.  Enable the
mode if ARG is nil, omitted, or is a positive number.  Disable the mode
if ARG is a negative number.

To check whether the minor mode is enabled in the current buffer,
evaluate `(default-value \\='typo-global-mode)'.

The mode's hook is called both when the mode is enabled and when it is
disabled.

(fn &optional ARG)" t)
(register-definition-prefixes "typo" '("define-typo-cycle" "typo-"))


;;; Generated autoloads from verifpal-mode.el

(register-definition-prefixes "verifpal-mode" '("verifpal-"))


;;; Generated autoloads from xr.el

(autoload 'xr "xr"
"Convert a regexp string to rx notation; the inverse of `rx'.
Passing the returned value to `rx' (or `rx-to-string') yields a regexp string
equivalent to RE-STRING.  DIALECT controls the choice of keywords,
and is one of:
`verbose'       -- verbose keywords
`medium' or nil -- somewhat verbose keywords (the default)
`brief'         -- short keywords
`terse'         -- very short keywords

(fn RE-STRING &optional DIALECT)")
(autoload 'xr-skip-set "xr"
"Convert a skip set string argument to rx notation.
SKIP-SET-STRING is interpreted according to the syntax of
`skip-chars-forward' and `skip-chars-backward' and converted to
a character class on `rx' form.
If desired, `rx' can then be used to convert the result to an
ordinary regexp.
See `xr' for a description of the DIALECT argument.

(fn SKIP-SET-STRING &optional DIALECT)")
(autoload 'xr-lint "xr"
"Detect dubious practices and possible mistakes in RE-STRING.
This includes uses of tolerated but discouraged constructs.
Outright regexp syntax violations are signalled as errors.

If PURPOSE is `file', perform additional checks assuming that RE-STRING
is used to match a file name.

If CHECKS is absent or nil, only perform checks that are very
likely to indicate mistakes; if `all', include all checks,
including ones more likely to generate false alarms.

Return a list of (OFFSET . COMMENT) where COMMENT applies at OFFSET
in RE-STRING.

(fn RE-STRING &optional PURPOSE CHECKS)")
(autoload 'xr-skip-set-lint "xr"
"Detect dubious practices and possible mistakes in SKIP-SET-STRING.
This includes uses of tolerated but discouraged constructs.
Outright syntax violations are signalled as errors.
The argument is interpreted according to the syntax of
`skip-chars-forward' and `skip-chars-backward'.
Return a list of (OFFSET . COMMENT) where COMMENT applies at OFFSET
in SKIP-SET-STRING.

(fn SKIP-SET-STRING)")
(autoload 'xr-pp "xr"
"Convert to `rx' notation and output the pretty-printed result.
This function uses `xr' to translate RE-STRING into DIALECT.
It is intended for use from an interactive elisp session.
See `xr' for a description of the DIALECT argument.

(fn RE-STRING &optional DIALECT)")
(autoload 'xr-skip-set-pp "xr"
"Convert a skip set string to `rx' notation and pretty-print.
This function uses `xr-skip-set' to translate SKIP-SET-STRING
into DIALECT.
It is intended for use from an interactive elisp session.
See `xr' for a description of the DIALECT argument.

(fn SKIP-SET-STRING &optional DIALECT)")
(register-definition-prefixes "xr" '("xr-"))

;;; End of scraped data

(provide '.user-lisp-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; .user-lisp-autoloads.el ends here
